version: '3.3'
services:

  flask:
    build: ./backend
    ports:
      - 8120:8120
    environment:
      INNOMETRICS_BACKEND_PATH: "/src/"
      PYTHONPATH: "$$INNOMETRICS_BACKEND_PATH:$$INNOMETRICS_BACKEND_PATH/api:$$INNOMETRICS_BACKEND_PATH/db"
      
    container_name: fl01
    command: bash -c "python launch.py"
    volumes:
      - ./backend:/src
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    # restart: on-failure
    environment:
      DOMAIN_ADDRESS: '"http://localhost:8120"' # Set your actual backend address 
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - flask
    command: npm run dev

  mongo:
    image: mongo
    # restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: metrics
      
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
   # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

    depends_on:
      - mongo
