export const TYPES = {

  INIT_ACTIVITIES: 'INIT_ACTIVITIES',

  GET_ACTIVITIES_REQUEST: 'GET_ACTIVITIES_REQUEST',
  GET_ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  GET_ACTIVITIES_FAILURE: 'GET_ACTIVITIES_FAILURE'
}